---

- hosts: all
  become: true
  tasks:

  - name: start httpd
    tags: apache, httpd
    service:
      name: httpd
      state: started

  - name: copy default html file for site
    tags: apache, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    